Repository Hyung-A/CollaTime_Project, pull requests merged in 2024-11, with the labels that each got.

#50 11/04_feature/45-EmailCode
  CollaTime/build.gradle
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/EmailConfig.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/MailConfig.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/SecurityConfig.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/MailDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/MailService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/controller/MailPageController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/service/UserService.java
  CollaTime/src/main/resources/templates/user/signup.html
Labels: function

#51 241105_feature/48-projectSpecificSelect
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
  CollaTime/src/main/resources/static/css/project/modalSelectProject.css
  CollaTime/src/main/resources/templates/project/ProjectMain.html
Labels: front, function

#59 Feature/58 delete project
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/SecurityConfig.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
  CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
  CollaTime/src/main/resources/static/css/project/image/exclamation mark.png
  CollaTime/src/main/resources/static/css/project/modalDeleteProject.css
  CollaTime/src/main/resources/static/css/project/modalUpdateProject.css
  CollaTime/src/main/resources/templates/auth/loginResult.html
  CollaTime/src/main/resources/templates/project/ProjectMain.html
  CollaTime/src/main/resources/templates/project/modalCreateOrJoin.html
  CollaTime/src/main/resources/templates/project/modalDeleteProject.html
  CollaTime/src/main/resources/templates/project/modalUpdateProject.html
  CollaTime/src/main/resources/templates/project/projectMain.html
  CollaTime_DB_Script.sql
Labels: front, function

#57 241106_feature/56-updateProject
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/SecurityConfig.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
  CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
  CollaTime/src/main/resources/static/css/project/modalUpdateProject.css
  CollaTime/src/main/resources/templates/auth/loginResult.html
  CollaTime/src/main/resources/templates/project/ProjectMain.html
  CollaTime/src/main/resources/templates/project/modalCreateOrJoin.html
  CollaTime/src/main/resources/templates/project/modalUpdateProject.html
  CollaTime/src/main/resources/templates/project/projectMain.html
  CollaTime_DB_Script.sql
Labels: function

#62 [feature]#60 project view 반환 방법 변경
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/SecurityConfig.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/resources/static/css/common/leftBar.css
  CollaTime/src/main/resources/static/css/project/modalDeleteProject.css
  CollaTime/src/main/resources/templates/auth/loginResult.html
  CollaTime/src/main/resources/templates/common/leftBar.html
  CollaTime/src/main/resources/templates/common/programHeader.html
  CollaTime/src/main/resources/templates/project/modalDeleteProject.html
  CollaTime/src/main/resources/templates/project/modalcreateorjoin.html
  CollaTime/src/main/resources/templates/project/modalcreateproject.html
  CollaTime/src/main/resources/templates/project/modaldatewarning.html
  CollaTime/src/main/resources/templates/project/modaldeleteproject.html
  CollaTime/src/main/resources/templates/project/modalinvitemember.html
  CollaTime/src/main/resources/templates/project/modalupdateproject.html
  CollaTime/src/main/resources/templates/project/projectmain.html
Labels: function

#63 241106_feature/52-스케줄 메인화면, 추가하기
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dao/ScheduleMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/servcie/ScheduleService.java
  CollaTime/src/main/resources/mappers/schedule/scheduleMapper.xml
  CollaTime/src/main/resources/static/css/schedule/main.css
  CollaTime/src/main/resources/static/css/schedule/makeschedule.css
  CollaTime/src/main/resources/templates/schedule/basic.html
  CollaTime/src/main/resources/templates/schedule/calendar.html
  CollaTime/src/main/resources/templates/schedule/list.html
  CollaTime/src/main/resources/templates/schedule/main.html
  CollaTime/src/main/resources/templates/schedule/makeschedule.html
  CollaTime/src/main/resources/templates/schedule/modifycheck.html
Labels: front, function

#64 11/06 Feature/61-myPageFront
  CollaTime/src/main/java/com/ohgiraffers/collatime/auth/controller/AuthController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/SecurityConfig.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/handler/AuthFailHandler.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/handler/AuthSuccessHandler.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/controller/MailPageController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/model/dto/MailDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/model/service/MailService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/controller/MypageController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/model/service/MypageService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/user/controller/UserController.java
  CollaTime/src/main/resources/static/css/mypage/image/dice.png
  CollaTime/src/main/resources/static/css/mypage/image/mail.png
  CollaTime/src/main/resources/static/css/mypage/image/sign.png
  CollaTime/src/main/resources/static/css/mypage/mypagemain.css
  CollaTime/src/main/resources/static/css/user/findIdAndPwd.css
  CollaTime/src/main/resources/templates/auth/login.html
  CollaTime/src/main/resources/templates/auth/loginfail.html
  CollaTime/src/main/resources/templates/auth/loginresult.html
  CollaTime/src/main/resources/templates/mypage/mypagemain.html
  CollaTime/src/main/resources/templates/user/findidandpwd.html
  CollaTime/src/main/resources/templates/user/signup.html
  CollaTime/src/main/resources/templates/user/signupresult.html
Labels: front

#71 241108_feature/69-sendInviteMail
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/resources/templates/project/projectmain.html
Labels: front, function

#73 11/08 Feature/72-modifyUser
  CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/controller/MypageController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/model/service/MypageService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/dao/UserMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/dto/UserDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/service/UserService.java
  CollaTime/src/main/resources/mappers/user/UserMapper.xml
  CollaTime/src/main/resources/static/css/mypage/modifyuser.css
  CollaTime/src/main/resources/static/css/mypage/myinqiury.css
  CollaTime/src/main/resources/static/css/mypage/mypagemain.css
  CollaTime/src/main/resources/static/css/mypage/resultsmallmodal.css
  CollaTime/src/main/resources/templates/mypage/modifyusermodal.html
  CollaTime/src/main/resources/templates/mypage/myinquiry.html
  CollaTime/src/main/resources/templates/mypage/mypagemain.html
  CollaTime/src/main/resources/templates/mypage/resultsmallmodal.html
  CollaTime/src/main/resources/templates/user/findidandpwd.html
  CollaTime/src/main/resources/templates/user/signup.html
Labels: front, function

#74 [feature]/#69-sendInviteMail
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/controller/MailPageController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/model/service/MailService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/InviteMemberDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/ProjectDTO.java
  CollaTime/src/main/resources/static/css/project/modalCreateProject.css
  CollaTime/src/main/resources/templates/project/projectmain.html
  CollaTime_DB_Script.sql
Labels: front, function

#78 [feature][project]/#69 Send_Invite_Mail
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/model/service/MailService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/InviteMemberDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/ProjectDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
  CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
  CollaTime/src/main/resources/static/css/project/modalCreateProject.css
  CollaTime/src/main/resources/static/css/project/modalInputAlert.css
  CollaTime/src/main/resources/static/css/project/modalInviteMember.css
  CollaTime/src/main/resources/templates/project/modalInputAlert.html
  CollaTime/src/main/resources/templates/project/projectmain.html
  CollaTime_DB_Script.sql
Labels: front, function

#83 [feature][mypage]/#82 Profile_Random
  CollaTime/src/main/java/com/ohgiraffers/collatime/common/MainController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/SecurityConfig.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/controller/MypageController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/dao/UserMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/service/UserService.java
  CollaTime/src/main/resources/mappers/user/UserMapper.xml
  CollaTime/src/main/resources/static/css/common/profile.css
  CollaTime/src/main/resources/templates/common/profile.html
  CollaTime/src/main/resources/templates/mypage/mypagemain.html
  CollaTime_DB_Script.sql
Labels: front, function

#88 [Feature][schedule]/#76 scheulde 조회
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dto/joinScheduleDTO.java
  CollaTime/src/main/resources/static/css/schedule/createsuccess.css
  CollaTime/src/main/resources/static/css/schedule/empty.css
  CollaTime/src/main/resources/static/css/schedule/list.css
  CollaTime/src/main/resources/templates/schedule/calendar.html
  CollaTime/src/main/resources/templates/schedule/createsuccess.html
  CollaTime/src/main/resources/templates/schedule/empty.html
  CollaTime/src/main/resources/templates/schedule/list.html
  CollaTime/src/main/resources/templates/schedule/makeschedule.html
Labels: front, function

#90 [Feature][common]#84 LeftBar 및 회원가입 유효성
  CollaTime/src/main/resources/static/css/common/leftBar.css
  CollaTime/src/main/resources/static/css/common/profile.css
  CollaTime/src/main/resources/static/css/mypage/mypagemain.css
  CollaTime/src/main/resources/templates/common/leftBar.html
  CollaTime/src/main/resources/templates/common/programHeader.html
  CollaTime/src/main/resources/templates/mypage/mypagemain.html
  CollaTime/src/main/resources/templates/user/signup.html
Labels: front, function

#92 [feature][project]/#91 Modal_Manage_Member
  CollaTime/src/main/resources/static/css/project/modalManageMember.css
  CollaTime/src/main/resources/templates/project/modalManageMember.html
  CollaTime/src/main/resources/templates/project/projectmain.html
Labels: front

#93 [feature][schedule]/#76 스케줄 조회
  CollaTime/src/main/resources/static/css/schedule/empty.css
  CollaTime/src/main/resources/static/css/schedule/makeschedule.css
  CollaTime/src/main/resources/templates/schedule/ca.html
  CollaTime/src/main/resources/templates/schedule/calendar.html
  CollaTime/src/main/resources/templates/schedule/empty.html
  CollaTime/src/main/resources/templates/schedule/makeschedule.html
Labels: front, function

#97 [feature][schedule]#76- 스케줄 상세 조회 창 구현
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dto/ScheduleDTO.java
  CollaTime/src/main/resources/mappers/schedule/scheduleMapper.xml
  CollaTime/src/main/resources/static/css/schedule/calendar.css
  CollaTime/src/main/resources/static/css/schedule/details.css
  CollaTime/src/main/resources/static/css/schedule/list.css
  CollaTime/src/main/resources/static/css/schedule/makeschedule.css
  CollaTime/src/main/resources/templates/schedule/ca.html
  CollaTime/src/main/resources/templates/schedule/calendar.html
  CollaTime/src/main/resources/templates/schedule/details.html
  CollaTime/src/main/resources/templates/schedule/makeschedule.html
Labels: front, function

#96 [feature][project]/#91 Modal_Manage_Member
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/ManageMemberDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/MemberListDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
  CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
  CollaTime/src/main/resources/static/css/project/image/trashcanIcon.png
  CollaTime/src/main/resources/static/css/project/modalManageMember.css
  CollaTime/src/main/resources/templates/common/profile.html
  CollaTime/src/main/resources/templates/project/modalManageMember.html
  CollaTime/src/main/resources/templates/project/projectmain.html
Labels: front, function

#99 [feature][project]/#91 Modal_Manage_Member
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/ManageMemberDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
  CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
  CollaTime/src/main/resources/static/css/project/modalManageMember.css
  CollaTime/src/main/resources/templates/project/projectmain.html
Labels: front, function

#104 [feature][schedule] /#76 스케줄 상세 조회 창 구현
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
  CollaTime/src/main/resources/templates/schedule/calendar.html
  CollaTime/src/main/resources/templates/schedule/details.html
Labels: function

#113 Feature/111 admin dashboard
  CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dto/AdminDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/service/AdminService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/handler/AuthSuccessHandler.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/controller/InquiryController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/dao/InquiryMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/service/InquiryService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/visit/controller/VisitController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/visit/model/dao/VisitMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/visit/model/dto/VisitDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/visit/model/service/VisitService.java
  CollaTime/src/main/resources/mappers/inquiry/InquiryMapper.xml
  CollaTime/src/main/resources/mappers/visit/VisitMapper.xml
  CollaTime/src/main/resources/static/css/admin/adminleftbar.css
  CollaTime/src/main/resources/static/css/admin/dashboard.css
  CollaTime/src/main/resources/static/css/admin/image/inquiry.png
  CollaTime/src/main/resources/static/css/admin/image/달력.png
  CollaTime/src/main/resources/static/css/common/passauthority.css
  CollaTime/src/main/resources/templates/admin/adminleftbar.html
  CollaTime/src/main/resources/templates/admin/base.html
  CollaTime/src/main/resources/templates/admin/dashboard.html
  CollaTime/src/main/resources/templates/admin/inquiry.html
  CollaTime/src/main/resources/templates/common/passauthority.html
  CollaTime/src/main/resources/templates/user/signup.html
Labels: front, function

#108 [feature][inquiry]#107 PassAuth
  CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/controller/InquiryController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/dao/InquiryMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/service/InquiryService.java
  CollaTime/src/main/resources/mappers/inquiry/InquiryMapper.xml
  CollaTime/src/main/resources/static/css/common/passauthority.css
  CollaTime/src/main/resources/templates/common/passauthority.html
Labels: function

#114 [feature][project]/#110 Update_Layout
  CollaTime/src/main/resources/static/css/project/modalComplete.css
  CollaTime/src/main/resources/static/css/project/modalDateWarning.css
  CollaTime/src/main/resources/templates/project/modalComplete.html
  CollaTime/src/main/resources/templates/project/modaldatewarning.html
  CollaTime/src/main/resources/templates/project/projectmain.html
Labels: front

#117 [feature][exception]/#115 Error_Page
  CollaTime/src/main/java/com/ohgiraffers/collatime/exception/controller/ExceptionHandlingController.java
  CollaTime/src/main/resources/static/css/exception/error403page.css
  CollaTime/src/main/resources/static/css/exception/error404page.css
  CollaTime/src/main/resources/static/css/exception/error500page.css
  CollaTime/src/main/resources/static/css/exception/image/errorImage.png
  CollaTime/src/main/resources/templates/exception/error400page.html
  CollaTime/src/main/resources/templates/exception/error403page.html
  CollaTime/src/main/resources/templates/exception/error404page.html
  CollaTime/src/main/resources/templates/exception/error500page.html
Labels: front, function

#124 [feature][schedule]/#121 Schedule_CRUD
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/service/ScheduleService.java
  CollaTime/src/main/resources/static/css/schedule/delete.css
  CollaTime/src/main/resources/static/css/schedule/deletecheck.css
  CollaTime/src/main/resources/static/css/schedule/details.css
  CollaTime/src/main/resources/templates/schedule/calendar.html
  CollaTime/src/main/resources/templates/schedule/createsuccess.html
  CollaTime/src/main/resources/templates/schedule/delete.html
  CollaTime/src/main/resources/templates/schedule/deletecheck.html
  CollaTime/src/main/resources/templates/schedule/details.html
  CollaTime/src/main/resources/templates/schedule/empty.html
  CollaTime/src/main/resources/templates/schedule/list.html
Labels: front, function

#128 [feature][schedule] #127 프로젝트,스케줄 연동
  CollaTime/src/main/resources/static/css/schedule/calendar.css
  CollaTime/src/main/resources/templates/project/projectmain.html
  CollaTime/src/main/resources/templates/schedule/calendar.html
Labels: function

#126 [feature][main]/#125 Main_Page
  CollaTime/src/main/resources/static/css/common/footer.css
  CollaTime/src/main/resources/static/css/common/header.css
  CollaTime/src/main/resources/static/css/common/image/collaTimeInage2.jpg
  CollaTime/src/main/resources/static/css/common/image/collaboration.jpg
  CollaTime/src/main/resources/static/css/common/image/easyIcon.png
  CollaTime/src/main/resources/static/css/common/main.css
  CollaTime/src/main/resources/templates/common/footer.html
  CollaTime/src/main/resources/templates/common/header.html
  CollaTime/src/main/resources/templates/common/main.html
Labels: front, function

#132 [feature][project]/#110 Update_Project_Layout
  CollaTime/src/main/java/com/ohgiraffers/collatime/exception/controller/ExceptionHandlingController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
  CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
  CollaTime/src/main/resources/static/css/common/image/collaTimeInage2.jpg
  CollaTime/src/main/resources/static/css/common/image/collaboration.jpg
  CollaTime/src/main/resources/static/css/common/image/collaborationImage.jpg
  CollaTime/src/main/resources/static/css/common/image/collaborationPNG.png
  CollaTime/src/main/resources/static/css/common/image/easyIcon.png
  CollaTime/src/main/resources/static/css/common/leftBar.css
  CollaTime/src/main/resources/static/css/project/modalCreateProject.css
  CollaTime/src/main/resources/static/css/project/projectMain.css
  CollaTime/src/main/resources/templates/auth/loginresult.html
  CollaTime/src/main/resources/templates/common/leftBar.html
  CollaTime/src/main/resources/templates/common/main.html
  CollaTime/src/main/resources/templates/common/programHeader.html
  CollaTime/src/main/resources/templates/common/resultinquirymodal.html
  CollaTime/src/main/resources/templates/exception/error400page.html
  CollaTime/src/main/resources/templates/exception/error403page.html
  CollaTime/src/main/resources/templates/exception/error404page.html
  CollaTime/src/main/resources/templates/exception/error500page.html
  CollaTime/src/main/resources/templates/exception/errorectpage.html
  CollaTime/src/main/resources/templates/project/modalcreateorjoin.html
  CollaTime/src/main/resources/templates/project/projectmain.html
Labels: front

#135 [feature][admin]/#131 Admin_Project_Control
  CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminProjectMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/service/AdminService.java
  CollaTime/src/main/resources/mappers/admin/AdminProjectMapper.xml
  CollaTime/src/main/resources/templates/admin/project.html
Labels: function

#137 [feature][main]/#125 Update_Main_Page
  CollaTime/src/main/resources/static/css/common/image/projectPage.png
  CollaTime/src/main/resources/static/css/common/main.css
  CollaTime/src/main/resources/templates/common/leftBar.html
  CollaTime/src/main/resources/templates/common/main.html
  CollaTime/src/main/resources/templates/project/projectmain.html
Labels: front

#146 [feature][project]/#110 Update_Project
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/InviteMemberDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/MemberListDTO.java
  CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
  CollaTime/src/main/resources/static/css/project/modalSelectProjectData.css
  CollaTime/src/main/resources/templates/exception/error400page.html
  CollaTime/src/main/resources/templates/exception/error403page.html
  CollaTime/src/main/resources/templates/exception/error404page.html
  CollaTime/src/main/resources/templates/exception/error500page.html
  CollaTime/src/main/resources/templates/exception/errorectpage.html
  CollaTime/src/main/resources/templates/project/projectmain.html
  CollaTime_DB_Script.sql
Labels: front, function

#148 [feature][schedule]/#147 Schedule_Choose_Member_And_Complete_Layout
  CollaTime CreateDB.sql
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dao/ScheduleMapper.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dto/ScheduleDTO.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/service/ScheduleService.java
  CollaTime/src/main/resources/mappers/schedule/scheduleMapper.xml
  CollaTime/src/main/resources/static/css/schedule/alertModalConfirm.css
  CollaTime/src/main/resources/static/css/schedule/calendar.css
  CollaTime/src/main/resources/static/css/schedule/details.css
  CollaTime/src/main/resources/static/css/schedule/empty.css
  CollaTime/src/main/resources/static/css/schedule/list.css
  CollaTime/src/main/resources/static/css/schedule/makeschedule.css
  CollaTime/src/main/resources/static/js/schedule/calendar.js
  CollaTime/src/main/resources/static/js/schedule/details.js
  CollaTime/src/main/resources/static/js/schedule/makeschedule.js
  CollaTime/src/main/resources/templates/schedule/alertModal.html
  CollaTime/src/main/resources/templates/schedule/calendar.html
  CollaTime/src/main/resources/templates/schedule/createsuccess.html
  CollaTime/src/main/resources/templates/schedule/details.html
  CollaTime/src/main/resources/templates/schedule/makeschedule.html
  CollaTime/src/main/resources/templates/schedule/modify.html
  CollaTime_DB_Script.sql
Labels: front, function

#151 [feature][auth/user/admin/mypage]/#150 Final_Organize
  CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/service/AdminService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/auth/controller/AuthController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/auth/model/AuthDetails.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/auth/model/service/AuthService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/common/MainController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/SecurityConfig.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/handler/AuthFailHandler.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/handler/AuthSuccessHandler.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/controller/InquiryController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/service/InquiryService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/controller/MailPageController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mail/model/service/MailService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/controller/MypageController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/model/service/MypageService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/user/controller/UserController.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/service/UserService.java
  CollaTime/src/main/java/com/ohgiraffers/collatime/visit/model/service/VisitService.java
  CollaTime/src/main/resources/static/css/admin/adminleftbar.css
  CollaTime/src/main/resources/static/css/admin/base.css
  CollaTime/src/main/resources/static/css/admin/dashboard.css
  CollaTime/src/main/resources/static/css/admin/deleteuser.css
  CollaTime/src/main/resources/static/css/admin/inquiry.css
  CollaTime/src/main/resources/static/css/admin/inquiryanswer.css
  CollaTime/src/main/resources/static/css/admin/project.css
  CollaTime/src/main/resources/static/css/admin/user.css
  CollaTime/src/main/resources/static/css/common/doinquiry.css
  CollaTime/src/main/resources/static/css/common/leftBar.css
  CollaTime/src/main/resources/static/css/common/passauthority.css
  CollaTime/src/main/resources/static/css/common/resultdoinquirymodal.css
  CollaTime/src/main/resources/static/css/mypage/deleteuser.css
  CollaTime/src/main/resources/static/css/mypage/modifyuser.css
  CollaTime/src/main/resources/static/css/mypage/myinqiury.css
  CollaTime/src/main/resources/static/css/mypage/myinquiryinfo.css
  CollaTime/src/main/resources/static/css/mypage/mypagemain.css
  CollaTime/src/main/resources/static/css/mypage/resultsmallmodal.css
  CollaTime/src/main/resources/static/css/user/findIdAndPwd.css
  CollaTime/src/main/resources/static/css/user/login.css
  CollaTime/src/main/resources/static/css/user/signup.css
  CollaTime/src/main/resources/templates/admin/base.html
  CollaTime/src/main/resources/templates/admin/dashboard.html
  CollaTime/src/main/resources/templates/admin/deleteinquiry.html
  CollaTime/src/main/resources/templates/admin/deleteproject.html
  CollaTime/src/main/resources/templates/admin/deleteresult.html
  CollaTime/src/main/resources/templates/admin/deleteuser.html
  CollaTime/src/main/resources/templates/admin/inquiry.html
  CollaTime/src/main/resources/templates/admin/inquiryanswer.html
  CollaTime/src/main/resources/templates/admin/inquiryinfo.html
  CollaTime/src/main/resources/templates/admin/inquiryresult.html
  CollaTime/src/main/resources/templates/admin/project.html
  CollaTime/src/main/resources/templates/admin/user.html
  CollaTime/src/main/resources/templates/auth/login.html
  CollaTime/src/main/resources/templates/common/leftBar.html
  CollaTime/src/main/resources/templates/common/passauthority.html
  CollaTime/src/main/resources/templates/common/profile.html
  CollaTime/src/main/resources/templates/mypage/modifyusermodal.html
  CollaTime/src/main/resources/templates/mypage/myinquiryinfo.html
  CollaTime/src/main/resources/templates/mypage/mypagemain.html
  CollaTime/src/main/resources/templates/user/findidandpwd.html
  CollaTime/src/main/resources/templates/user/signup.html
Labels: front

#153 [feature][project]/#152 Final_Project
  CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
  CollaTime/src/main/resources/static/css/common/header.css
  CollaTime/src/main/resources/static/css/common/image/apple-touch-icon.png
  CollaTime/src/main/resources/static/css/common/image/favicon.ico
  CollaTime/src/main/resources/static/css/common/image/newFavicon.ico
  CollaTime/src/main/resources/static/css/common/leftBar.css
  CollaTime/src/main/resources/static/css/common/main.css
  CollaTime/src/main/resources/static/css/common/programHeader.css
  CollaTime/src/main/resources/static/css/project/modalComplete.css
  CollaTime/src/main/resources/static/css/project/modalCreateOrJoin.css
  CollaTime/src/main/resources/static/css/project/modalCreateProject.css
  CollaTime/src/main/resources/static/css/project/modalDateWarning.css
  CollaTime/src/main/resources/static/css/project/modalDeleteProject.css
  CollaTime/src/main/resources/static/css/project/modalInputAlert.css
  CollaTime/src/main/resources/static/css/project/modalInviteMember.css
  CollaTime/src/main/resources/static/css/project/modalIsRealDeleteMember.css
  CollaTime/src/main/resources/static/css/project/modalManageMember.css
  CollaTime/src/main/resources/static/css/project/modalMoreInviteMember.css
  CollaTime/src/main/resources/static/css/project/modalSelectProjectData.css
  CollaTime/src/main/resources/static/css/project/modalUpdateProject.css
  CollaTime/src/main/resources/static/css/project/modalWrongJoinCode.css
  CollaTime/src/main/resources/static/css/project/projectMain.css
  CollaTime/src/main/resources/templates/common/footer.html
  CollaTime/src/main/resources/templates/common/main.html
  CollaTime/src/main/resources/templates/project/projectmain.html
  CollaTime_DB_Script.sql
Labels: front

#155 [feature][project/main]/#154 Apply_Font
  COLLABORATION_GUIDE.md
  CollaTime/src/main/resources/static/css/common/main.css
  CollaTime/src/main/resources/static/css/mypage/mypagemain.css
  CollaTime/src/main/resources/static/css/project/modalCreateOrJoin.css
  CollaTime/src/main/resources/static/css/project/modalCreateProject.css
  CollaTime/src/main/resources/static/css/project/modalDateWarning.css
  CollaTime/src/main/resources/static/css/project/modalInviteMember.css
  CollaTime/src/main/resources/static/css/project/modalMoreInviteMember.css
  CollaTime/src/main/resources/static/css/project/modalSelectProjectData.css
  CollaTime/src/main/resources/static/css/project/modalUpdateProject.css
  CollaTime/src/main/resources/static/css/project/projectMain.css
  CollaTime/src/main/resources/static/css/project/reset.css
  CollaTime/src/main/resources/templates/common/main.html
  CollaTime_DB_Script.sql
Labels: front

#159 [feature][main]/#158 Final_Main_Page
  CollaTime/src/main/resources/mappers/inquiry/InquiryMapper.xml
  CollaTime/src/main/resources/static/css/common/footer.css
  CollaTime/src/main/resources/static/css/common/header.css
  CollaTime/src/main/resources/static/css/common/image/mainSchedule.png
  CollaTime/src/main/resources/static/css/common/image/schedulePage.png
  CollaTime/src/main/resources/static/css/common/main.css
  CollaTime/src/main/resources/static/css/project/projectMain.css
  CollaTime/src/main/resources/templates/common/main.html
  CollaTime/src/main/resources/templates/project/projectmain.html
  CollaTime_DB_Script.sql
Labels: front

#160 [feature][schedule]/#157 Schedule_Final
  CollaTime/src/main/resources/static/css/schedule/alertModalConfirm.css
  CollaTime/src/main/resources/static/css/schedule/calendar.css
  CollaTime/src/main/resources/static/css/schedule/createsuccess.css
  CollaTime/src/main/resources/static/css/schedule/delete.css
  CollaTime/src/main/resources/static/css/schedule/deletecheck.css
  CollaTime/src/main/resources/static/css/schedule/details.css
  CollaTime/src/main/resources/static/css/schedule/empty.css
  CollaTime/src/main/resources/static/css/schedule/list.css
  CollaTime/src/main/resources/static/css/schedule/makeschedule.css
  CollaTime/src/main/resources/static/css/schedule/modify.css
  CollaTime/src/main/resources/static/css/schedule/modifycheck.css
  CollaTime/src/main/resources/static/js/schedule/details.js
  CollaTime/src/main/resources/static/js/schedule/makeschedule.js
  CollaTime/src/main/resources/templates/schedule/alertModal.html
  CollaTime/src/main/resources/templates/schedule/calendar.html
  CollaTime/src/main/resources/templates/schedule/createsuccess.html
  CollaTime/src/main/resources/templates/schedule/delete.html
  CollaTime/src/main/resources/templates/schedule/deletecheck.html
  CollaTime/src/main/resources/templates/schedule/details.html
  CollaTime/src/main/resources/templates/schedule/empty.html
  CollaTime/src/main/resources/templates/schedule/list.html
  CollaTime/src/main/resources/templates/schedule/makeschedule.html
  CollaTime/src/main/resources/templates/schedule/modify.html
  CollaTime/src/main/resources/templates/schedule/modifycheck.html
Labels: front, function

#167 [feature][schedule]/#165 Schedule_Css_Update
  CollaTime/src/main/resources/static/css/schedule/details.css
  CollaTime/src/main/resources/static/css/schedule/makeschedule.css
Labels: front

#168 [feature][totla]/#166 Total_Final
  CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/controller/MypageController.java
  CollaTime/src/main/resources/templates/project/projectmain.html
  CollaTime_DB_Script.sql
Labels: front

#170 [feature][schedule]/#169 Calendar_Css_Update
  CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
  CollaTime/src/main/resources/static/css/schedule/calendar.css
Labels: front
